#pragma once
//#include <universal/com_memory.h>
#define WP_NONE 0
enum weapType_t
{                                       
    WEAPTYPE_BULLET,
    WEAPTYPE_GRENADE,
    WEAPTYPE_PROJECTILE,
    WEAPTYPE_BINOCULARS,
    WEAPTYPE_NUM,
};
enum weapClass_t
{                                       
    WEAPCLASS_RIFLE,
    WEAPCLASS_MG,
    WEAPCLASS_SMG,
    WEAPCLASS_SPREAD,
    WEAPCLASS_PISTOL,
    WEAPCLASS_GRENADE,
    WEAPCLASS_ROCKETLAUNCHER,
    WEAPCLASS_TURRET,
    WEAPCLASS_NON_PLAYER,
    WEAPCLASS_ITEM,
    WEAPCLASS_NUM,
};
enum PenetrateType 
{                                       
    PENETRATE_TYPE_NONE,
    PENETRATE_TYPE_SMALL,
    PENETRATE_TYPE_MEDIUM,
    PENETRATE_TYPE_LARGE,
    PENETRATE_TYPE_COUNT,
};
enum ImpactType 
{                                       
    IMPACT_TYPE_NONE,
    IMPACT_TYPE_BULLET_SMALL,
    IMPACT_TYPE_BULLET_LARGE,
    IMPACT_TYPE_BULLET_AP,
    IMPACT_TYPE_SHOTGUN,
    IMPACT_TYPE_GRENADE_BOUNCE,
    IMPACT_TYPE_GRENADE_EXPLODE,
    IMPACT_TYPE_ROCKET_EXPLODE,
    IMPACT_TYPE_PROJECTILE_DUD,
    IMPACT_TYPE_COUNT,
};
enum weapInventoryType_t
{                                       
    WEAPINVENTORY_PRIMARY,
    WEAPINVENTORY_OFFHAND,
    WEAPINVENTORY_ITEM,
    WEAPINVENTORY_ALTMODE,
    WEAPINVENTORYCOUNT,
};
enum weapFireType_t 
{                                       
    WEAPON_FIRETYPE_FULLAUTO,
    WEAPON_FIRETYPE_SINGLESHOT,
    WEAPON_FIRETYPE_BURSTFIRE2,
    WEAPON_FIRETYPE_BURSTFIRE3,
    WEAPON_FIRETYPE_BURSTFIRE4,
    WEAPON_FIRETYPECOUNT,
};
enum weapStance_t 
{                                       
    WEAPSTANCE_STAND,
    WEAPSTANCE_DUCK,
    WEAPSTANCE_PRONE,
    WEAPSTANCE_NUM,
};
enum activeReticleType_t 
{                                       
    VEH_ACTIVE_RETICLE_NONE,
    VEH_ACTIVE_RETICLE_PIP_ON_A_STICK,
    VEH_ACTIVE_RETICLE_BOUNCING_DIAMOND,
    VEH_ACTIVE_RETICLE_COUNT,
};
enum weaponIconRatioType_t 
{                                       
    WEAPON_ICON_RATIO_1TO1,
    WEAPON_ICON_RATIO_2TO1,
    WEAPON_ICON_RATIO_4TO1,
    WEAPON_ICON_RATIO_COUNT,
};
enum ammoCounterClipType_t 
{                                       
    AMMO_COUNTER_CLIP_NONE,
    AMMO_COUNTER_CLIP_MAGAZINE,
    AMMO_COUNTER_CLIP_SHORTMAGAZINE,
    AMMO_COUNTER_CLIP_SHOTGUN,
    AMMO_COUNTER_CLIP_ROCKET,
    AMMO_COUNTER_CLIP_BELTFED,
    AMMO_COUNTER_CLIP_ALTWEAPON,
    AMMO_COUNTER_CLIP_COUNT,
};
enum weapOverlayReticle_t 
{                                       
    WEAPOVERLAYRETICLE_NONE,
    WEAPOVERLAYRETICLE_CROSSHAIR,
    WEAPOVERLAYRETICLE_NUM,
};
enum WeapOverlayInteface_t 
{                                       
    WEAPOVERLAYINTERFACE_NONE,
    WEAPOVERLAYINTERFACE_JAVELIN,
    WEAPOVERLAYINTERFACE_TURRETSCOPE,
    WEAPOVERLAYINTERFACECOUNT,
};
enum weapProjExposion_t 
{                                       
    WEAPPROJEXP_GRENADE,
    WEAPPROJEXP_ROCKET,
    WEAPPROJEXP_FLASHBANG,
    WEAPPROJEXP_NONE,
    WEAPPROJEXP_DUD,
    WEAPPROJEXP_SMOKE,
    WEAPPROJEXP_HEAVY,
    WEAPPROJEXP_NUM,
};
enum WeapStickinessType 
{                                       
    WEAPSTICKINESS_NONE,
    WEAPSTICKINESS_ALL,
    WEAPSTICKINESS_GROUND,
    WEAPSTICKINESS_GROUND_WITH_YAW,
    WEAPSTICKINESS_COUNT,
};
enum guidedMissileType_t 
{                                       
    MISSILE_GUIDANCE_NONE,
    MISSILE_GUIDANCE_SIDEWINDER,
    MISSILE_GUIDANCE_HELLFIRE,
    MISSILE_GUIDANCE_JAVELIN,
    MISSILE_GUIDANCE_COUNT,
};
enum OffhandSecondaryClass 
{
    PLAYER_OFFHAND_SECONDARY_SMOKE,
    PLAYER_OFFHAND_SECONDARY_FLASH,
    PLAYER_OFFHAND_SECONDARIES_TOTAL,
};
enum weaponstate_t 
{                                       
    WEAPON_READY,
    WEAPON_RAISING,
    WEAPON_RAISING_ALTSWITCH,
    WEAPON_DROPPING,
    WEAPON_DROPPING_QUICK,
    WEAPON_FIRING,
    WEAPON_RECHAMBERING,
    WEAPON_RELOADING,
    WEAPON_RELOADING_INTERUPT,
    WEAPON_RELOAD_START,
    WEAPON_RELOAD_START_INTERUPT,
    WEAPON_RELOAD_END,
    WEAPON_MELEE_INIT,
    WEAPON_MELEE_FIRE,
    WEAPON_MELEE_END,
    WEAPON_OFFHAND_INIT,
    WEAPON_OFFHAND_PREPARE,
    WEAPON_OFFHAND_HOLD,
    WEAPON_OFFHAND_START,
    WEAPON_OFFHAND,
    WEAPON_OFFHAND_END,
    WEAPON_DETONATING,
    WEAPON_SPRINT_RAISE,
    WEAPON_SPRINT_LOOP,
    WEAPON_SPRINT_DROP,
    WEAPON_NIGHTVISION_WEAR,
    WEAPON_NIGHTVISION_REMOVE,
    WEAPONSTATES_NUM,
};
enum OffhandClass 
{                                       
    OFFHAND_CLASS_NONE,
    OFFHAND_CLASS_FRAG_GRENADE,
    OFFHAND_CLASS_SMOKE_GRENADE,
    OFFHAND_CLASS_FLASH_GRENADE,
    OFFHAND_CLASS_COUNT,
};
// bg_weapons_load_obj
struct SurfaceTypeSoundList 
{
    char *surfaceSoundBase;
    struct snd_alias_list_t **soundAliasList;
};